
framework:
    secret: '%env(APP_SECRET)%'

    session: true

    #esi: true
    #fragments: true

    router:
        utf8: true
        annotations: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
